apiVersion: v1
kind: Pod
metadata:
  labels:
    role: web-frontend
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs
